Repository SeongTeam/hoodone, pull requests merged in 2024-08, with the labels that each got.

#132 Hotfix_front error
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/favorite/entities/sb_favorite.entity.ts
  back/main_sever/src/favorite/favorite.service.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/const/user-find-options.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.service.ts
  front/.env.production_sample
  front/.env.sample
  front/src/app/sb/create/[questId]/page.tsx
  front/src/atoms/userAccount.ts
  front/src/components/authentication/login.tsx
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/common/FavoriteButton.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/postAction.dto.ts
  front/src/components/posts/postLib.ts
  front/src/components/posts/postsActions.ts
  front/src/lib/Date.ts
  front/src/lib/server-only/authLib.ts
  front/src/server-actions/AuthAction.ts
  front/src/type/AuthType.ts
  shared/index.ts
  shared/response-dto/auth-api-response.dto.ts
  shared/response-dto/quest-post-api-response.dto.ts
  shared/response-dto/sb-post-api-response.dto.ts
Labels: Nest.js, fix, AuthModule, postsModule, UserModule, Next.js

#133 Add logic saving backend app log as file
  back/main_sever/package-lock.json
  back/main_sever/package.json
  back/main_sever/src/_common/common.module.ts
  back/main_sever/src/_common/filter/common-exception.filter.ts
  back/main_sever/src/_common/middleware/logger-context.middleware.ts
  back/main_sever/src/app.module.ts
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/main.ts
  back/main_sever/src/utils/winston.config.ts
Labels: Nest.js, feature

#134 <Deploy> docker-compose & DockerFile 추가
  .dockerignore
  back/main_sever/Dockerfile
  back/main_sever/package.json
  docker-compose.yml
  front/Dockerfile
  front/next.config.mjs
  shared/Dockerfile
Labels: deploy, Docker

#135 <Feature> Logging Interceptor
  back/main_sever/src/_common/common.module.ts
  back/main_sever/src/_common/interceptor/logging.interceptor.ts
  back/main_sever/src/_common/provider/LoggerUsecase.ts
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/utils/winston.config.ts
Labels: Nest.js, feature
