Repository SeongTeam/hoodone, pull requests merged in 2024-07, with the labels that each got.

#89 <Feature> Rewrite Post Upload logic
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.service.ts
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/quest/create/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/atoms/comment.ts
  front/src/atoms/post.ts
  front/src/atoms/userAccount.ts
  front/src/components/common/ImageUpload.tsx
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/posts/card/LoadMorePostCards.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/imageUpload.tsx
  front/src/components/posts/create/postFormat/subComponent/creationRulesBox.tsx
  front/src/components/posts/create/postFormat/subComponent/imageInput.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
  front/src/components/posts/view/postMenu.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/hooks/useSelectFile.tsx
  front/src/lib/server-only/authLib.ts
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  front/src/type/postType.ts
  front/src/utils/cloudinary/lib.ts
  shared/response-dto/auth-api-response.dto.ts
Labels: Nest.js, refactoring, feature, AuthModule, Next.js

#93 <Feature>/sb detail
  front/src/app/quest/[postid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/posts/card/LoadMorePostCards.tsx
  front/src/components/posts/card/MiniPostCard.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/RuleCard.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/components/ParentPostCard.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/utils/chakra/customColors.ts
Labels: Next.js

#97 <Feature>[front] Add post fetch logic with fixxing and refactoring front logic
  front/src/app/api/posts/route.ts
  front/src/app/quest/[postid]/page.tsx
  front/src/app/quest/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/app/sb/create/page.tsx
  front/src/app/sb/page.tsx
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/modal/auth/authModal.tsx
  front/src/components/modal/auth/login.tsx
  front/src/components/naviBar/navibar.tsx
  front/src/components/posts/card/AdminPostCard.tsx
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/card/LoadMorePostCards.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/PostSliderWindow.tsx
  front/src/components/posts/card/PostWindow.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/view/postMenu.tsx
  front/src/components/sidebar/Sidebar.tsx
  front/src/hooks/userAccount.tsx
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  front/src/utils/chakra/componentStyle/tag.ts
  front/src/utils/chakra/theme.ts
  front/src/utils/cloudinary/mockUpData.ts
Labels: refactoring, feature, fix, Next.js

#98 Favorite 로직 추가
  back/main_sever/src/app.module.ts
  back/main_sever/src/favorite/entities/quest_favorite.entity.ts
  back/main_sever/src/favorite/entities/sb_favorite.entity.ts
  back/main_sever/src/favorite/favorite.module.ts
  back/main_sever/src/favorite/favorite.service.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-quest/quest_post.service.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/posts/entities/quest_post.entity.ts
  back/main_sever/src/posts/entities/sb_post.entity.ts
  back/main_sever/src/posts/post.module.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/_tickets/entities/ticket.entity.ts
  back/main_sever/src/users/_tickets/ticket.module.ts
  back/main_sever/src/users/_tickets/ticket.service.ts
  back/main_sever/src/users/_tickets/usecase/ticket_use_case.ts
  back/main_sever/src/users/const/user-find-options.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.module.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, postsModule, UserModule

#99 <Fix> front logic
  back/main_sever/src/_common/dto/dtoUtils.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/dto/update-post.dto.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  front/src/app/quest/[postid]/edit/page.tsx
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/modal/auth/authModal.tsx
  front/src/components/modal/auth/components/input/button_and_inputs.tsx
  front/src/components/modal/auth/signUp.tsx
  front/src/components/naviBar/navibar.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/view/postMenu.tsx
  front/src/components/sidebar/SideBarRoute.tsx
  front/src/components/sidebar/components/Links.tsx
  front/src/hooks/userAccount.tsx
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  front/src/utils/cloudinary/cldImage.tsx
Labels: fix, postsModule, Next.js

#100 <fix>[front] fix next build error
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/modal/auth/authModal.tsx
  front/src/components/naviBar/components/searchBar.tsx
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/card/PostSliderWindow.tsx
  front/src/components/posts/card/PostWindow.tsx
Labels: fix, Next.js

#101 Feature/back favorite
  back/main_sever/src/auth/guard/token/bearer-token.guard.ts
  back/main_sever/src/favorite/entities/quest_favorite.entity.ts
  back/main_sever/src/favorite/entities/sb_favorite.entity.ts
  back/main_sever/src/favorite/favorite.service.ts
  back/main_sever/src/posts/-comment/comment.controller.ts
  back/main_sever/src/posts/-comment/enum/post_type.ts
  back/main_sever/src/posts/-comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/guard/quest-post-owner.guard.ts
  back/main_sever/src/posts/guard/sb-post-owner.guard.ts
  back/main_sever/src/posts/pips/post-id.pip.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, postsModule

#103 Feature/front favorite
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/posts/-comment/comment.service.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  front/src/app/quest/[postid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/atoms/userAccount.ts
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  shared/response-dto/post-api-reponse.dto.ts
Labels: Nest.js, CommentModule, Next.js

#104 <Fix>[front] Fix front error
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/comment/deletedCommentItem.tsx
  front/src/components/comment/replyToggleButton.tsx
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/commentItemtList.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/components/common/ProfileImage.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/lib/server-only/postLib.ts
Labels: refactoring, fix, Next.js

#106 <Fix>[back][front] comment logic
  back/main_sever/src/posts/-comment/comment.service.ts
  back/main_sever/src/posts/-comment/const/comment-find-options.const.ts
  back/main_sever/src/posts/-comment/entities/comment.entity.ts
  back/main_sever/src/posts/entities/sb_post.entity.ts
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/commentItemtList.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/components/common/ImageUpload.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/server-actions/commentAction.ts
  front/src/utils/chakra/componentStyle/button.ts
Labels: fix, CommentModule

#107 <fix>[front] Fix favorite post logic
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/detail/detailPostForm.tsx
Labels: fix, Next.js

#108 <Fix><refactor>[front] Fix and Refactor front logic
  front/src/app/api/posts/route.ts
  front/src/app/page.tsx
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/quest/[postid]/edit/page.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/atoms/comment.ts
  front/src/atoms/post.ts
  front/src/components/_global/slider/postSlider.tsx
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/posts/card/AdminPostCard.tsx
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/card/MiniPostCard.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/PostSliderWindow.tsx
  front/src/components/posts/card/PostWindow.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/common/FavoriteButton.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/components/ParentPostCard.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/view/postMenu.tsx
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  front/src/type/postType.ts
Labels: refactoring, fix, Next.js

#109 <Fix>[front] sb create logic
  front/src/app/sb/create/[questId]/page.tsx
  front/src/app/sb/create/layout.tsx
  front/src/app/sb/create/page.tsx
  front/src/components/posts/card/const/rule_card_texts.ts
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/subComponent/creationRulesBox.tsx
  front/src/components/posts/detail/components/ParentPostCard.tsx
  front/src/server-actions/postsActions.ts
  front/src/type/postType.ts
Labels: fix, Next.js

#110 <Feature>[back][front] sb vote logic
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/posts/const/post-find-options.const.ts
  back/main_sever/src/posts/entities/sb_post.entity.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  front/src/app/quest/[postid]/page.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/postsActions.ts
  front/src/type/server-action/responseType.ts
  shared/index.ts
  shared/response-dto/post-api-reponse.dto.ts
  shared/response-dto/quest-post-api-response.dto.ts
Labels: Nest.js, fix, postsModule, Next.js

#112 [DEPLOY]Feature/aws setting
  back/main_sever/.gitignore
  back/main_sever/ecosystem.config.js
  back/main_sever/package.json
  back/main_sever/src/app.controller.ts
  back/main_sever/src/app.module.ts
  front/ecosystem.config.js
  front/package.json
Labels: deploy

#114 Refactor project
  back/main_sever/package.json
  front/package.json
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/commentItemtList.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/lib/server-only/commentLib.ts
  shared/README.md
Labels: refactoring

#115 <Fix>[front] fix front warning and error
  front/next.config.mjs
  front/src/app/page.tsx
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/components/_global/slider/postSlider.tsx
  front/src/components/posts/card/PostSliderWindow.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/report/ReportModal.tsx
Labels: fix

#116 <Refactor>[front] code and folder structure
  front/src/app/api/posts/route.ts
  front/src/app/authentication/reset-password/page.tsx
  front/src/app/authentication/sign-in/page.tsx
  front/src/app/authentication/sign-up/page.tsx
  front/src/app/page.tsx
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/quest/[postid]/edit/page.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/quest/create/page.tsx
  front/src/app/quest/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/app/sb/create/[questId]/page.tsx
  front/src/app/sb/page.tsx
  front/src/components/authentication/components/button_and_inputs.tsx
  front/src/components/authentication/components/common_input.tsx
  front/src/components/authentication/components/timer.tsx
  front/src/components/authentication/components/toast.tsx
  front/src/components/authentication/login.tsx
  front/src/components/authentication/resetPassword.tsx
  front/src/components/authentication/signUp.tsx
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/comment/deletedCommentItem.tsx
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/common/postSlider.tsx
  front/src/components/modal/auth/authInput.tsx
  front/src/components/modal/auth/authModal.tsx
  front/src/components/posts/card/AdminPostCard.tsx
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/card/MiniPostCard.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/PostSliderWindow.tsx
  front/src/components/posts/card/PostWindow.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/common/FavoriteButton.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
  front/src/components/posts/create/tab.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/components/ParentPostCard.tsx
  front/src/components/posts/detail/components/postMenu.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/postLib.ts
  front/src/components/posts/postType.ts
  front/src/components/posts/postsActions.ts
  front/src/components/report/ReportModal.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/server-actions/AuthAction.ts
  front/src/server-actions/commentAction.ts
  front/src/server-actions/reportAction.ts
  front/src/type/AuthType.ts
  front/src/type/commentType.ts
  front/src/type/responseType.ts
  front/src/utils/cloudinary/lib.ts
Labels: refactoring, Next.js

#117 <fix>[front] fix build error
  front/src/components/comment/server-component/commentArea.tsx
Labels: Next.js, build error

#118 <Feature>[front][back] post delete logic
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-quest/quest_post.service.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  front/src/app/quest/[postid]/error.tsx
  front/src/app/quest/[postid]/not-found.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/sb/[postid]/error.tsx
  front/src/app/sb/[postid]/not-found.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/components/posts/detail/components/postMenu.tsx
  front/src/components/posts/postsActions.ts
  shared/response-dto/post-api-reponse.dto.ts
Labels: Nest.js, feature, postsModule, Next.js

#120 <refactor>[front] correct log format
  front/src/components/posts/postLib.ts
  front/src/lib/server-only/authLib.ts
Labels: refactoring, Next.js

#119 Feature/admin quest logic
  back/main_sever/src/_common/const/env-keys.const.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-quest/quest_post.service.ts
  back/main_sever/src/posts/pips/post-id.pip.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
Labels: Nest.js, postsModule

#122 <Fix>[front] fix front logic and UI
  front/src/app/authentication/layout.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/components/authentication/login.tsx
  front/src/components/authentication/signUp.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/naviBar/components/LoginButton.tsx
  front/src/components/naviBar/components/UseMenuIcons.tsx
  front/src/components/naviBar/components/UserMenu.tsx
  front/src/components/naviBar/navibar.tsx
  front/src/components/posts/card/MiniPostCard.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/card/components/postThumbnail.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/components/ParentPostCard.tsx
  front/src/components/posts/detail/components/postMenu.tsx
  front/src/components/posts/detail/detailPostForm.tsx
  front/src/components/posts/postLib.ts
  front/src/components/posts/postType.ts
  front/src/components/sidebar/SideBarRoute.tsx
  front/src/components/sidebar/components/Links.tsx
  front/src/server-actions/AuthAction.ts
Labels: Nest.js, fix, Next.js

#124 <Fix>[front] init build error
  front/src/app/api/auth/route.ts
  front/src/app/api/auth/signup/route.ts
  front/src/app/api/route.ts
  front/src/components/posts/postsActions.ts
  front/src/lib/middleware/jwt-middleware.ts
  front/src/middleware.ts
Labels: fix, Next.js

#125 <doc> Modify project documnents
  README.md
  back/main_sever/.env.sample
  front/.env.sample
Labels: documentation

#121 Feature/apply tickee logic on post use case
  back/main_sever/src/auth/guard/token/bearer-token.guard.ts
  back/main_sever/src/posts/-quest/quest_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/users/_tickets/ticket.module.ts
  back/main_sever/src/users/const/user-find-options.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, postsModule, UserModule, Ticket Module

#127 <fix> solve postUse logic
  back/main_sever/src/posts/usecase/post.use-case.ts
Labels: Nest.js, postsModule

#128 <fix> show Admin post on front
  front/src/components/posts/card/AdminPostSliderWidnow.tsx
  front/src/components/posts/postLib.ts
Labels: feature, rest API, Next.js

#129 Refactoring/deploy email and start option
  back/main_sever/package.json
  back/main_sever/src/mail/templates/email.hbs
Labels: Nest.js, refactoring, deploy

#130 <doc> Add App strcuture diagram
  README.md
Labels: documentation
