Repository SeongTeam/hoodone, pull requests merged in 2024-06, with the labels that each got.

#66 <feature> Add getCompareTempUserPinCode & resetPassword DTOs
  shared/response-dto/auth-api-response.dto.ts
Labels: rest API, shared

#67 Feature/change reset password modal
  front/src/app/api/auth/registered-email/route.ts
  front/src/app/api/auth/reset-password/route.ts
  front/src/components/modal/auth/resetPassword.tsx
Labels: feature, rest API, Next.js

#69 <feature> modify AuthService.signToken()
  back/main_sever/src/auth/auth.service.ts
Labels: Nest.js, AuthModule

#70 Improve Comment Logic
  front/src/atoms/comment.ts
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentArea.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/comment/deletedCommentItem.tsx
  front/src/components/comment/replyToggleButton.tsx
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/commentItemtList.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/server-actions/commentAction.ts
Labels: feature, Next.js

#71 Featrue keeping user authorization
  back/main_sever/src/auth/usecase/auth.use-case.ts
  front/src/app/post/create/page.tsx
  front/src/atoms/comment.ts
  front/src/atoms/userAccount.ts
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/modal/auth/authModal.tsx
  front/src/components/modal/auth/login.tsx
  front/src/components/naviBar/rightContent/rightContent.tsx
  front/src/components/naviBar/rightContent/userMenu.tsx
  front/src/hooks/userAccount.tsx
  front/src/server-actions/AuthAction.ts
  front/src/server-actions/commentAction.ts
  shared/response-dto/auth-api-response.dto.ts
Labels: Nest.js, feature, fix, AuthModule, Next.js

#72 Fix infinite scroll bug
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/posts/view/loadMorePosts.tsx
Labels: fix, Next.js

#73 <Fix>[front] post loading logic
  front/src/app/api/posts/route.ts
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/posts/view/loadMorePosts.tsx
  front/src/lib/server-only/postLib.ts
Labels: bug, fix, Next.js

#74 <fix>[front] fix create post logic
  front/src/server-actions/postsActions.ts
Labels: fix, Next.js

#75 Refactoring/change to server action
  front/src/app/api/auth/registered-email/route.ts
  front/src/app/api/auth/reset-password/route.ts
  front/src/components/modal/auth/resetPassword.tsx
  front/src/server-actions/AuthAction.ts
Labels: rest API, Next.js

#76 [Back]Feature/add incoding reset password logic
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/users/usecase/user.use-case.ts
Labels: Nest.js, AuthModule, UserModule

#77 <feature>[Back] Add board logic
  back/main_sever/src/app.module.ts
  back/main_sever/src/boards/boards.controller.ts
  back/main_sever/src/boards/boards.module.ts
  back/main_sever/src/boards/boards.service.ts
  back/main_sever/src/boards/const/board-find-option.const.ts
  back/main_sever/src/boards/dto/create-board.dto.ts
  back/main_sever/src/boards/entities/board.entity.ts
  back/main_sever/src/boards/usecase/board.use-case.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/posts/post.controller.ts
  back/main_sever/src/posts/post.module.ts
  back/main_sever/src/posts/post.service.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/entities/user.entity.ts
Labels: Nest.js, feature, postsModule, BoardModule

#78 Feature/ Quest & sb Post 테이블 추가후 로직 변경
  back/main_sever/src/app.module.ts
  back/main_sever/src/auth/auth.service.ts
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/common/interceptor/transaction.interceptor.ts
  back/main_sever/src/common/middleware/quest-exists.middleware.ts
  back/main_sever/src/common/middleware/sb-exists.middleware.ts
  back/main_sever/src/posts/-comment/comment.controller.ts
  back/main_sever/src/posts/-comment/comment.module.ts
  back/main_sever/src/posts/-comment/comment.service.spec.ts
  back/main_sever/src/posts/-comment/comment.service.ts
  back/main_sever/src/posts/-comment/commentREAD.md
  back/main_sever/src/posts/-comment/const/comment-find-options.const.ts
  back/main_sever/src/posts/-comment/dto/create-comment.dto.ts
  back/main_sever/src/posts/-comment/dto/create-reply-comment.dto.ts
  back/main_sever/src/posts/-comment/dto/update-comment.dto.ts
  back/main_sever/src/posts/-comment/entities/comment.entity.ts
  back/main_sever/src/posts/-comment/guard/comment-owner.guard.ts
  back/main_sever/src/posts/-comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/-quest/quest.controller.ts
  back/main_sever/src/posts/-quest/quest_post.service.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/posts/comment/comment.controller.spec.ts
  back/main_sever/src/posts/comment/dto/create-comment.dto.ts
  back/main_sever/src/posts/const/post-create-options.const.ts
  back/main_sever/src/posts/const/post-find-options.const.ts
  back/main_sever/src/posts/dto/create-post.dto.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/posts/entities/quest_post.entity.ts
  back/main_sever/src/posts/entities/sb_post.entity.ts
  back/main_sever/src/posts/guard/quest-post-owner.guard.ts
  back/main_sever/src/posts/guard/sb-post-owner.guard.ts
  back/main_sever/src/posts/pips/post-id.pip.ts
  back/main_sever/src/posts/post.controller.spec.ts
  back/main_sever/src/posts/post.module.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/const/user-find-options.ts
  back/main_sever/src/users/entities/temp-user.entity.ts
  back/main_sever/src/users/entities/user.entity.ts
Labels: Nest.js, feature, rest API, postsModule, decorator, CommentModule

#80 Quest & sb Post로 테이블을 나눈 후 생긴 문제 해결
  back/main_sever/src/common/middleware/sb-exists.middleware.ts
  back/main_sever/src/posts/-comment/comment.controller.ts
  back/main_sever/src/posts/-comment/comment.service.ts
  back/main_sever/src/posts/pips/post-id.pip.ts
Labels: fix, postsModule, CommentModule

#81 Rewrite layout
  front/package-lock.json
  front/package.json
  front/public/smallQuest/cube.svg
  front/src/app/globals.css
  front/src/app/layout.tsx
  front/src/app/page.tsx
  front/src/components/comment/comment.tsx
  front/src/components/posts/create/tab.tsx
  front/src/components/posts/view/postListItem.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/components/sidebar/Sidebar.tsx
  front/src/components/sidebar/components/Content.tsx
  front/src/components/sidebar/components/Links.tsx
  front/src/components/sidebar/components/Panel.tsx
  front/src/utils/chakra/componentStyle/Inputs.ts
  front/src/utils/chakra/componentStyle/button.ts
  front/src/utils/chakra/customColors.ts
  front/src/utils/chakra/fonts.ts
  front/src/utils/chakra/foundations/colorMode.ts
  front/src/utils/chakra/foundations/fonts.ts
  front/src/utils/chakra/theme.ts
Labels: feature, Next.js

#82 Feature/create postPage 개발 quest & sb로 폴더 나눔
  front/src/app/post/[postid]/page.tsx
  front/src/app/post/create/layout.tsx
  front/src/app/post/create/page.tsx
  front/src/app/post/layout.tsx
  front/src/app/quest/[postid]/comment/[commentid]/page.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/quest/create/page.tsx
  front/src/app/sb/[postid]/comment/[commentid]/page.tsx
  front/src/app/sb/[postid]/page.tsx
  front/src/app/sb/create/page.tsx
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/const/texts.tsx
  front/src/components/posts/create/postFormat/subComponent/creationRulesBox.tsx
  front/src/components/posts/create/postFormat/subComponent/textEditor.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
  front/src/server-actions/postsActions.ts
  front/src/utils/chakra/componentStyle/Inputs.ts
Labels: Next.js

#83 <Rewrite><Fix> Implement New <Navibar/> and <Sidebar/> for Mobile and Fix overlapping bug
  front/src/app/layout.tsx
  front/src/components/naviBar/components/LoginButton.tsx
  front/src/components/naviBar/components/UseMenuIcons.tsx
  front/src/components/naviBar/components/UserMenu.tsx
  front/src/components/naviBar/components/searchBar.tsx
  front/src/components/naviBar/navibar.tsx
  front/src/components/naviBar/rightContent/authButtons.tsx
  front/src/components/naviBar/rightContent/icons.tsx
  front/src/components/naviBar/rightContent/rightContent.tsx
  front/src/components/naviBar/rightContent/userMenu.tsx
  front/src/components/naviBar/searchBar.tsx
  front/src/components/sidebar/SideBarDrawer.tsx
  front/src/components/sidebar/SideBarRoute.tsx
  front/src/components/sidebar/Sidebar.tsx
  front/src/components/sidebar/components/Content.tsx
  front/src/components/sidebar/components/Links.tsx
  front/src/components/sidebar/components/Panel.tsx
Labels: feature, fix, Next.js

#84 Tag logic 추가
  back/main_sever/src/posts/dto/create-post.dto.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  front/src/atoms/post.ts
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/textInput.tsx
Labels: Nest.js, Next.js

#87 <feature>[front][back] ReWrite post PostlistItem Logic
  back/main_sever/src/auth/dto/register-user.dto.ts
  back/main_sever/src/common/validation-message/password-vaildation.message.ts
  back/main_sever/src/posts/-comment/const/comment-find-options.const.ts
  back/main_sever/src/posts/-quest/quest_post.service.ts
  back/main_sever/src/posts/-sb-post/sb_post.service.ts
  back/main_sever/src/posts/const/post-create-options.const.ts
  back/main_sever/src/posts/const/post-find-options.const.ts
  back/main_sever/src/posts/dto/create-post.dto.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/users.controller.ts
  front/src/atoms/post.ts
  front/src/components/common/server-component/UserProfileImage.tsx
  front/src/components/common/server-component/centerCard.tsx
  front/src/components/naviBar/components/searchBar.tsx
  front/src/components/posts/card/LoadMorePostCards.tsx
  front/src/components/posts/card/PostCard.tsx
  front/src/components/posts/card/components/QuestButtons.tsx
  front/src/components/posts/card/components/postThumbnail.tsx
  front/src/components/posts/view/postList.tsx
  front/src/components/posts/view/postListItem.tsx
  front/src/components/posts/view/postMenu.tsx
  front/src/components/posts/view/server-component/postThumbnail.tsx
  front/src/lib/Date.ts
Labels: bug, Nest.js, feature, fix, Next.js

#88 <Feature> DetailPost 추가
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/posts/-comment/comment.controller.ts
  back/main_sever/src/posts/-quest/quest.controller.ts
  back/main_sever/src/posts/-sb-post/sb_post.controller.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/users/users.controller.ts
  front/src/app/layout.tsx
  front/src/app/quest/[postid]/page.tsx
  front/src/app/quest/create/page.tsx
  front/src/components/_global/slider/postSliber.tsx
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/server-component/commentArea.tsx
  front/src/components/comment/server-component/rootCommentItemList.tsx
  front/src/components/posts/card/MiniPostCard.tsx
  front/src/components/posts/card/RuleCard.tsx
  front/src/components/posts/card/const/rule_card_texts.ts
  front/src/components/posts/create/createPostForm.tsx
  front/src/components/posts/create/postFormat/subComponent/creationRulesBox.tsx
  front/src/components/posts/detail/components/DetailPostHeader.tsx
  front/src/components/posts/detail/detailPostForm.tsx
Labels: Next.js
