Repository SeongTeam/hoodone, pull requests merged in 2024-03, with the labels that each got.

#7 <doc> 초기 PR 템플릿 추가
  doc/pull_request_template.md
Labels: documentation

#8 <doc> Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#10 <fix >Delete back/main_sever/package-lock.json
  back/main_sever/package-lock.json
Labels: bug, fix

#9 <feature>JWT auth 로직 추가
  back/main_sever/.prettierrc
  back/main_sever/package-lock.json
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/auth.module.ts
  back/main_sever/src/auth/auth.service.ts
  back/main_sever/src/auth/dto/auth-credential.dto.ts
  back/main_sever/src/common/const/env-keys.const.ts
  back/main_sever/src/configs/typeorm.config.ts
  back/main_sever/src/users/entity/user.entity.ts
  back/main_sever/src/users/user.repository.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.module.ts
  back/main_sever/src/users/users.service.spec.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, feature, auth

#17 <Refactoring> change user entity name
  back/main_sever/src/auth/auth.service.ts
  back/main_sever/src/auth/dto/auth-credential.dto.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/user.repository.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.module.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, refactoring

#16 Feature add common interceptor
  back/main_sever/src/common/decorator/query-runner.decorator.ts
  back/main_sever/src/common/entity/base.entity.ts
  back/main_sever/src/common/interceptor/transaction.interceptor.ts
Labels: Nest.js, feature, common service

#18 <feature> Add User.decorator
  back/main_sever/src/users/decorator/user.decorator.ts
Labels: Nest.js, feature, decorator

#19 <Feature> Comment Module 추가
  back/main_sever/src/app.module.ts
  back/main_sever/src/common/const/env-keys.const.ts
  back/main_sever/src/common/decorator/is-public.decorator.ts
  back/main_sever/src/common/entity/base.entity.ts
  back/main_sever/src/common/middleware/post-exists.middleware.ts
  back/main_sever/src/common/validation-message/number-vaildation.message.ts
  back/main_sever/src/posts/comment/comment.controller.spec.ts
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.module.ts
  back/main_sever/src/posts/comment/comment.service.spec.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/commentREAD.md
  back/main_sever/src/posts/comment/const/default-comment-find-options.const.ts
  back/main_sever/src/posts/comment/const/default-response-comment-find-options.const.ts
  back/main_sever/src/posts/comment/dto/create-comment.dto.ts
  back/main_sever/src/posts/comment/dto/create-response-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comments.entity.ts
  back/main_sever/src/posts/comment/entities/response_comments.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/entities/posts.entity.ts
  back/main_sever/src/users/const/default_qurey_user_options.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, feature, rest API, decorator, CommentModule

#20 <Feature> ResponseCommentModel 삭제
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.module.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/commentREAD.md
  back/main_sever/src/posts/comment/const/default-response-comment-find-options.const.ts
  back/main_sever/src/posts/comment/dto/create-response-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comments.entity.ts
  back/main_sever/src/posts/comment/entities/response_comments.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
Labels: Nest.js, feature, CommentModule

#22 <Refactory> change name to Post
  back/main_sever/src/app.module.ts
  back/main_sever/src/common/middleware/post-exists.middleware.ts
  back/main_sever/src/posts/comment/comment.module.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/const/default-comment-find-options.const.ts
  back/main_sever/src/posts/comment/dto/create-comment.dto.ts
  back/main_sever/src/posts/comment/dto/create-response-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comment.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/const/default-post-find-options.const.ts
  back/main_sever/src/posts/dto/create-post.dto.ts
  back/main_sever/src/posts/dto/update-post.dto.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/posts/post.controller.spec.ts
  back/main_sever/src/posts/post.controller.ts
  back/main_sever/src/posts/post.module.ts
  back/main_sever/src/posts/post.service.spec.ts
  back/main_sever/src/posts/post.service.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
  back/main_sever/src/users/entities/user.entity.ts
Labels: Nest.js, refactoring

#23 <refactoring>Change name to ReplyComment
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/dto/create-reply-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comment.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
Labels: refactoring, CommentModule

#24 <style> prettier code format 적용
  back/main_sever/src/app.module.ts
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/auth.module.ts
  back/main_sever/src/auth/auth.service.ts
  back/main_sever/src/auth/dto/auth-credential.dto.ts
  back/main_sever/src/auth/guard/basic-token.guard.ts
  back/main_sever/src/auth/guard/bearer-token.guard.ts
  back/main_sever/src/common/const/env-keys.const.ts
  back/main_sever/src/common/decorator/is-public.decorator.ts
  back/main_sever/src/common/decorator/query-runner.decorator.ts
  back/main_sever/src/common/entity/base.entity.ts
  back/main_sever/src/common/middleware/post-exists.middleware.ts
  back/main_sever/src/common/validation-message/email-validation.message.ts
  back/main_sever/src/common/validation-message/length-validation.message.ts
  back/main_sever/src/common/validation-message/number-vaildation.message.ts
  back/main_sever/src/common/validation-message/password-vaildation.message.ts
  back/main_sever/src/common/validation-message/string-validation.message.ts
  back/main_sever/src/configs/typeorm.config.ts
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.module.ts
  back/main_sever/src/posts/comment/dto/create-comment.dto.ts
  back/main_sever/src/posts/comment/dto/create-reply-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comment.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/const/default-post-find-options.const.ts
  back/main_sever/src/posts/dto/create-post.dto.ts
  back/main_sever/src/posts/dto/update-post.dto.ts
  back/main_sever/src/posts/entities/post.entity.ts
  back/main_sever/src/posts/post.controller.ts
  back/main_sever/src/posts/post.module.ts
  back/main_sever/src/posts/post.service.ts
  back/main_sever/src/users/const/default_qurey_user_options.ts
  back/main_sever/src/users/decorator/user.decorator.ts
  back/main_sever/src/users/entities/user.entity.ts
  back/main_sever/src/users/user.repository.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.module.ts
  back/main_sever/src/users/users.service.spec.ts
  back/main_sever/test/app.e2e-spec.ts
Labels: Nest.js, style
