Repository SeongTeam/hoodone, pull requests merged in 2024-05, with the labels that each got.

#43 <Feature>Add getBy Email & email backend APIs
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/users/usecase/user.use-case.ts
  back/main_sever/src/users/users.controller.ts
Labels: Nest.js, UserModule

#44 <feature>[Back]change exception message property
  back/main_sever/src/common/filter/common-exception.filter.ts
Labels: Nest.js, common service

#46 Feature add check jwt expired
  back/main_sever/src/auth/auth.service.ts
  back/main_sever/src/common/exception/auth-exception.ts
  back/main_sever/src/common/exception/common/const/error-code/exception-error-code.const.ts
  back/main_sever/src/common/exception/common/const/message/exception.message.ts
  back/main_sever/src/common/exception/common/enum/auth-exception-code.enum.ts
Labels: Nest.js, feature, AuthModule, common service

#47 <feature>[front] Add Basic middleware
  front/src/middleware.ts
Labels: Next.js, middleware

#48 <feature>Add jwtMiddleware
  front/src/app/middleware/jwt-middleware.ts
  front/src/middleware.ts
Labels: Next.js, middleware

#49 <feature>[Back] Add logic for accessing paginated posts
  back/main_sever/src/posts/dto/get-paginated-posts.dto.ts
  back/main_sever/src/posts/post.controller.ts
  back/main_sever/src/posts/post.service.ts
  back/main_sever/src/posts/usecase/post.use-case.ts
Labels: Nest.js, postsModule

#51 Fix post read logic
  front/package-lock.json
  front/package.json
  front/src/app/post/[postid]/page.tsx
  front/src/lib/server-only/postLib.ts
  shared/response-dto/post-api-reponse.dto.ts
Labels: bug, refactoring, fix, Next.js

#52 Modify related to Sign-In logic
  front/package-lock.json
  front/package.json
  front/src/app/api/auth/login/route.ts
  front/src/app/post/create/page.tsx
  front/src/atoms/authModal.ts
  front/src/atoms/userAccount.ts
  front/src/components/modal/auth/authModal.tsx
  front/src/components/modal/auth/login.tsx
  front/src/components/naviBar/navibar.tsx
  front/src/components/naviBar/rightContent/rightContent.tsx
  front/src/components/naviBar/rightContent/userMenu.tsx
  front/src/components/naviBar/searchBar.tsx
  front/src/middleware.ts
  front/src/server-actions/AuthAction.ts
  front/src/utils/chakra/componentStyle/button.ts
  front/src/utils/recoil/recoild-persist.ts
Labels: refactoring, feature, fix, Next.js

#53 <Feature>[Back] 가입 이메일 인증 로직 추가
  back/main_sever/nest-cli.json
  back/main_sever/package.json
  back/main_sever/src/app.module.ts
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/auth.module.ts
  back/main_sever/src/auth/guard/token/basic-token.guard.ts
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/common/exception/auth-exception.ts
  back/main_sever/src/common/exception/common/base.exception.ts
  back/main_sever/src/common/filter/common-exception.filter.ts
  back/main_sever/src/mail/mail.controller.ts
  back/main_sever/src/mail/mail.module.ts
  back/main_sever/src/mail/mail.service.ts
  back/main_sever/src/mail/templates/email.hbs
  back/main_sever/src/mail/usecase/mail.usecase.ts
  back/main_sever/src/users/entities/temp-user.entity.ts
  back/main_sever/src/users/usecase/temp-user.case.ts
  back/main_sever/src/users/users.controller.ts
  back/main_sever/src/users/users.module.ts
  back/main_sever/src/users/users.service.ts
Labels: Nest.js, AuthModule, UserModule

#56 Feature apply signup
  back/main_sever/src/app.module.ts
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/usecase/auth.use-case.ts
  back/main_sever/src/common/const/env-keys.const.ts
  back/main_sever/src/mail/mail.module.ts
  back/main_sever/src/mail/mail.service.ts
  back/main_sever/src/mail/usecase/mail.usecase.ts
  back/main_sever/src/users/usecase/temp-user.case.ts
  back/main_sever/src/users/users.controller.ts
  front/src/components/modal/auth/signUp.tsx
  front/src/components/posts/view/server-component/postThumbnail.tsx
  front/src/lib/server-only/message.ts
  front/src/server-actions/AuthAction.ts
Labels: Nest.js, feature, rest API, Next.js

#57 Feature comment logic
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/dto/create-reply-comment.dto.ts
  back/main_sever/src/posts/comment/entities/comment.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
  back/main_sever/src/posts/post.controller.ts
  front/package-lock.json
  front/package.json
  front/src/app/post/[postid]/page.tsx
  front/src/atoms/commen.ts
  front/src/atoms/post.ts
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/commenItemtList.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentArea.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/lib/server-only/postLib.ts
  front/src/server-actions/commentAction.ts
  shared/package-lock.json
  shared/package.json
  shared/response-dto/comment-api-response.dto.ts
Labels: Nest.js, CommentModule, Next.js

#58 <feature>[front] Add accessToken refresh logic
  front/src/app/middleware/jwt-middleware.ts
  front/src/lib/middleware/jwt-middleware.ts
  front/src/lib/server-only/authLib.ts
  front/src/middleware.ts
  front/src/server-actions/AuthAction.ts
  front/src/server-actions/commentAction.ts
  front/src/server-actions/postsActions.ts
Labels: bug, feature, Next.js

#59 <Feature>[front> Add Timer & Toast
  front/src/components/modal/auth/components/timer.tsx
  front/src/components/modal/auth/components/toast/toast.tsx
  front/src/components/modal/auth/signUp.tsx
  front/src/server-actions/AuthAction.ts
Labels: React.js, feature, Next.js

#60 Feateure change modal UI
  front/src/components/modal/auth/authModal.tsx
  front/src/components/modal/auth/components/input/button_and_inputs.tsx
  front/src/components/modal/auth/components/input/common_input.tsx
  front/src/components/modal/auth/components/toast/toast.tsx
  front/src/components/modal/auth/login.tsx
  front/src/components/modal/auth/signUp.tsx
  front/src/utils/chakra/componentStyle/Inputs.ts
Labels: React.js, feature, Next.js

#61 <Feature> add temp user service
  back/main_sever/src/auth/auth.controller.ts
  back/main_sever/src/auth/dto/register-user.dto.ts
  back/main_sever/src/users/usecase/temp-user.case.ts
  back/main_sever/src/users/users.service.ts
  front/src/components/modal/auth/components/input/button_and_inputs.tsx
  front/src/components/modal/auth/components/input/common_input.tsx
Labels: Nest.js, AuthModule, Next.js

#62 <Fix> solve sign up modal
  front/src/components/modal/auth/components/input/button_and_inputs.tsx
  front/src/components/modal/auth/components/input/common_input.tsx
  front/src/components/modal/auth/login.tsx
  front/src/components/modal/auth/signUp.tsx
Labels: fix, Next.js

#63 Fix comment logic
  back/main_sever/src/common/entity/base.entity.ts
  back/main_sever/src/posts/comment/comment.controller.ts
  back/main_sever/src/posts/comment/comment.service.ts
  back/main_sever/src/posts/comment/entities/comment.entity.ts
  back/main_sever/src/posts/comment/usecase/comment.use-case.ts
  front/src/app/post/[postid]/comment/[commentid]/page.tsx
  front/src/app/post/[postid]/page.tsx
  front/src/atoms/commen.ts
  front/src/atoms/post.ts
  front/src/components/comment/InputComment.tsx
  front/src/components/comment/InputReply.tsx
  front/src/components/comment/commenItemtList.tsx
  front/src/components/comment/comment.tsx
  front/src/components/comment/commentArea.tsx
  front/src/components/comment/commentItem.tsx
  front/src/components/comment/commentMenu.tsx
  front/src/components/posts/view/server-component/post.tsx
  front/src/lib/server-only/commentLib.ts
  front/src/server-actions/commentAction.ts
Labels: Nest.js, feature, fix, common service, CommentModule, Next.js

#64 <fix>[back] Modify loading PostModel
  back/main_sever/src/posts/const/post-find-options.const.ts
Labels: Nest.js, fix, postsModule
